USE [master]
GO
/****** Object:  Database [sivek]    Script Date: 11.03.2024 10:33:50 ******/
CREATE DATABASE [sivek]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sivek', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\sivek.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sivek_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\sivek_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [sivek] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sivek].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [sivek] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [sivek] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [sivek] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [sivek] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [sivek] SET ARITHABORT OFF 
GO
ALTER DATABASE [sivek] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [sivek] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [sivek] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [sivek] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [sivek] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [sivek] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [sivek] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [sivek] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [sivek] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [sivek] SET  ENABLE_BROKER 
GO
ALTER DATABASE [sivek] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [sivek] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [sivek] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [sivek] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [sivek] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [sivek] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [sivek] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [sivek] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [sivek] SET  MULTI_USER 
GO
ALTER DATABASE [sivek] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [sivek] SET DB_CHAINING OFF 
GO
ALTER DATABASE [sivek] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [sivek] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [sivek] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [sivek] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [sivek] SET QUERY_STORE = OFF
GO
USE [sivek]
GO
/****** Object:  Table [dbo].[customer]    Script Date: 11.03.2024 10:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[customer](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[first_name] [varchar](50) NOT NULL,
	[last_name] [varchar](50) NOT NULL,
	[email] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[order_details]    Script Date: 11.03.2024 10:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[order_details](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[order_id] [int] NULL,
	[product_id] [int] NULL,
	[amount] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[orders]    Script Date: 11.03.2024 10:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[orders](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[customer_id] [int] NULL,
	[order_date] [datetime] NULL,
	[total_price] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[products]    Script Date: 11.03.2024 10:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[products](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[product_name] [varchar](50) NOT NULL,
	[price] [decimal](10, 2) NOT NULL,
	[is_available] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[review]    Script Date: 11.03.2024 10:33:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[review](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[product_id] [int] NULL,
	[customer_id] [int] NULL,
	[reviewtext] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[order_details]  WITH CHECK ADD FOREIGN KEY([order_id])
REFERENCES [dbo].[orders] ([id])
GO
ALTER TABLE [dbo].[order_details]  WITH CHECK ADD FOREIGN KEY([product_id])
REFERENCES [dbo].[products] ([id])
GO
ALTER TABLE [dbo].[orders]  WITH CHECK ADD FOREIGN KEY([customer_id])
REFERENCES [dbo].[customer] ([id])
GO
ALTER TABLE [dbo].[review]  WITH CHECK ADD FOREIGN KEY([customer_id])
REFERENCES [dbo].[customer] ([id])
GO
ALTER TABLE [dbo].[review]  WITH CHECK ADD FOREIGN KEY([product_id])
REFERENCES [dbo].[products] ([id])
GO
USE [master]
GO
ALTER DATABASE [sivek] SET  READ_WRITE 
GO
